# repo_checkout_branch
---
- name: "Pull changes on main branch"
  hosts: all
  gather_facts: true

  vars:
    repo_url: "{{ git_repo_url }}"
    repo_dest: "{{ git_repo_dest }}"
    gh_ssh_key: "{{ git_ssh_key }}"
    repo_checkout_branch: "main"

  tasks:
    - name: "Gather the package facts"
      ansible.builtin.package_facts:
        manager: auto

    - name: "Git pull main branch"
      ansible.builtin.import_role:
        name: my.weather_monorepo.git
        tasks_from: git-pull.yml
