---
- name: "Install project with uv"
  hosts: all
  gather_facts: true

  vars:
    repo_dest: "{{ git_repo_dest }}"

  tasks:
    - name: "Gather the package facts"
      ansible.builtin.package_facts:
        manager: auto

    - name: "Create virtualenv"
      ansible.builtin.import_role:
        name: my.weather_monorepo.python.astral_uv
        tasks_from: uv-create-venv.yml

    - name: "Install project"
      ansible.builtin.import_role:
        name: my.weather_monorepo.python.astral_uv
        tasks_from: uv-install-project.yml

    - name: "Sync project"
      ansible.builtin.import_role:
        name: my.weather_monorepo.python.astral_uv
        tasks_from: uv-sync-project.yml
