---
- name: "Install & configure git"
  hosts: all

  vars:
    git_default_branch: "{{ git_default_branch_name }}"
    git_user: "{{ git_user_name }}"
    git_email: "{{ git_user_email }}"

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.homelab.base_setup
        tasks_from: gather-facts.yml

    - name: "Call homelab collection's configure_git role"
      ansible.builtin.import_role:
        name: my.homelab.git
