---
- name: "Allow firewall ports"
  hosts: all

  vars:
    ufw_allow_tcp_ports: "{{ ufw_tcp_allowed_ports }}"
    ufw_allow_udp_ports: "{{ ufw_udp_allowed_ports }}"
    firewalld_allow_ports: "{{ firewalld_allowed_ports }}"

  tasks:
    - name: "Gather the package facts"
      ansible.builtin.import_role:
        name: my.homelab.base_setup
        tasks_from: gather-facts.yml

    - name: "Include homelab's firewall role, allow port tasks"
      ansible.builtin.import_role:
        name: my.homelab.firewall
        tasks_from: allow-ports.yml

    - name: "Include homelab collection's firewall service restart role"
      ansible.builtin.import_role:
        name: my.homelab.firewall
        tasks_from: enable-firewall.yml
