---
- name: "Enable firewall"
  hosts: all

  tasks:
    - name: "Gather the package facts"
      ansible.builtin.import_role:
        name: my.homelab.base_setup
        tasks_from: gather-facts.yml

    - name: "Include homelab collection's firewall enable role"
      ansible.builtin.import_role:
        name: my.homelab.security.firewall
        tasks_from: disable-firewall.yml
