---
- name: "Install firewall"
  hosts: all
  gather_facts: true

  tasks:
    - name: "Include homelab collection's firewall install role"
      ansible.builtin.import_role:
        name: my.homelab.security.firewall
