---
- name: "Run ansible_svc user setup"
  hosts: all
  gather_facts: true

  tasks:
    - name: "Call homelab collection's onboard role"
      ansible.builtin.import_role:
        name: my.homelab.onboard
