---
- name: "Remove ansible_svc user"
  hosts: all

  vars:
    remove_user: true

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.homelab.facts

    - name: "Call homelab collection's onboard role"
      ansible.builtin.import_role:
        name: my.homelab.onboard
