---
- name: "Remove ansible_svc user"
  hosts: all
  # become: true

  vars:
    remove_user: true

  tasks:
    - name: "Call homelab collection's onboard role"
      ansible.builtin.import_role:
        name: my.homelab.onboard
