---
- name: "Install pyenv & configure Python environment"
  hosts: all

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.homelab.base_setup
        tasks_from: gather-facts.yml

    - name: "Call homelab collection's pyenv setup role"
      ansible.builtin.import_role:
        name: my.homelab.python.pyenv
