---
- name: "Install pipx & common apps"
  hosts: all

  vars:
    python_bin: "/home/{{ remote_host_user }}/.pyenv/shims/python"
    pipx_bin: "/home/{{ remote_host_user }}/.pyenv/bin/pyenv exec pipx"
    pipx_apps_list: [pdm, ruff, nox]

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.homelab.facts

    ## If you don't want to install the "base" pipx app collection, comment this task out
    - name: "Call homelab collection's pipx role that installs common packages"
      ansible.builtin.import_role:
        name: my.homelab.python.pipx
        tasks_from: install-pipx-apps.yml
