---
- name: "Check if ~/.cargo/bin/uv exists"
  ansible.builtin.stat:
    path: "/home/{{ remote_host_user }}/.cargo/bin/uv"
  register: uv_bin

- name: "Check if {{ repo_dest }}/.venv exists"
  ansible.builtin.stat:
    path: "{{ repo_dest }}/.venv"
  register: venv_dir

- name: "Run 'uv venv' in project directory: {{ repo_dest }}"
  ansible.builtin.shell: |
    /home/{{ remote_host_user }}/.cargo/bin/uv venv
  args:
    executable: /bin/bash
    chdir: "{{ repo_dest }}"
  register: uv_venv_output
  changed_when: false
  become: true
  become_user: "{{ remote_host_user }}"
  when: (uv_bin.stat.exists) and (not venv_dir.stat.exists)

- name: "Display output of 'uv venv"
  ansible.builtin.debug:
    msg: "{{ uv_venv_output.stdout }}"
  when: (uv_bin.stat.exists) and (not venv_dir.stat.exists)
