---
- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "[DEBUG] Pyenv install check"
  ansible.builtin.debug:
    msg: "Found pyenv in packages: {{ 'pyenv' in ansible_facts.packages }}"

- name: "[DEBUG] Print pyenv path"
  ansible.builtin.debug:
    msg: "Pyenv path: /home/{{ remote_host_user }}/.pyenv"

- name: "Check if pyenv dir exists"
  ansible.builtin.stat:
    path: "/home/{{ remote_host_user }}/.pyenv"
  become: true
  register: pyenv_dir

- name: "Check if Python version already installed with pyenv (directory exists in pyenv path)"
  ansible.builtin.stat:
    path: "/home/{{ remote_host_user }}/.pyenv/versions/{{ pyenv_python_ver }}"
  become: true
  register: pyenv_ver_exists

- name: "[DEBUG] Pyenv python path exist check"
  ansible.builtin.debug:
    msg: "Pyenv Python path '{/home/{{ remote_host_user }}/.pyenv/{{ pyenv_python_ver }}}' exists: {{ pyenv_ver_exists }}"

- name: "Include pyenv dependency install tasks"
  ansible.builtin.include_tasks: install-dependencies.yml
  when: (ansible_facts['os_family'] == "Debian") and ("pyenv" not in ansible_facts.packages)

- name: "Include pyenv install tasks"
  ansible.builtin.include_tasks: install-pyenv.yml
  when: ("pyenv" not in ansible_facts.packages) and (not pyenv_dir.stat.exists)

- name: "Include pyenv configure tasks"
  ansible.builtin.include_tasks: configure-env.yml

- name: "Include pyenv tasks to set global Python version"
  ansible.builtin.include_tasks: pyenv-global-python.yml
