---
# tasks file for enable_zswap
- name: Enable zswap tweak for improved performance on Raspberry Pi 4+
  ansible.builtin.shell: |
    sed -i -e 's/$/ zswap.enabled=1/' /boot/firmware/cmdline.txt
  become: true
  become_user: root
  register: zswap_modified
  when: (ansible_architecture == "aarch64") and (ansible_distribution == "Ubuntu")
# - name: Reboot to apply zswap configuration
#   reboot:
#     msg: "Reboot initiated by Ansible."
#     # connection_timeout: 5
#     reboot_timeout: 300
#     pre_reboot_delay: 0
#     post_reboot_delay: 30
#   become: true
#   when: zswap_modified.rc == 0

# - name: Wait for reboot to complete
#   ansible.builtin.wait_for_connection:
#     connect_timeout: 10
#     sleep: 5
#     delay: 5
#     timeout: 300
#   become: true
#   when: (ansible_architecture == "aarch64") and (ansible_distribution == "Ubuntu")
