- name: Reboot Rpi4
  reboot:
    msg: "Reboot initiated by Ansible."
    # connection_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
  become: true
  when: (ansible_architecture == "aarch64") and (ansible_distribution == "Ubuntu")

- name: Wait for reboot to complete
  ansible.builtin.wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 300
  become: true
  when: (ansible_architecture == "aarch64") and (ansible_distribution == "Ubuntu")
