---
# https://raw.githubusercontent.com/aosm/clamav/master/clamav.Conf/clamd.conf.default
- name: "[ClamAV Setup] Check if /etc/clamav/clamd.conf exists"
  stat:
    path: "/etc/clamav/clamd.conf"
  become: true
  register: clamd_conf_file

- name: "[ClamAV Setup] Check if /etc/clamav/clamd.conf.orig exists"
  stat:
    path: "/etc/clamav/clamd.conf.orig"
  become: true
  register: clamd_conf_orig_file

- name: "[ClamAV Setup] Check if /etc/clamav/clamd.conf.bak exists"
  stat:
    path: "/etc/clamav/clamd.conf.bak"
  become: true
  register: clamd_conf_bak_file

- name: "[ClamAV Setup] Backup original /etc/clamav/clamd.conf"
  copy:
    src: "/etc/clamav/clamd.conf"
    dest: "/etc/clamav/clamd.conf.orig"
  become: true
  when: (clamd_conf_file.stat.exists == true) and (clamd_conf_orig_file.stat.exists != true)

- name: "[ClamAV Setup] Backup /etc/clamav/clamd.conf"
  copy:
    src: "/etc/clamav/clamd.conf"
    dest: "/etc/clamav/clamd.conf.bak"
  become: true
  when: (clamd_conf_file.stat.exists == true)

- name: "[ClamAV Setup] Copy clamd.conf to remote"
  copy:
    src: files/clamd.conf
    dest: /etc/clamav/clamd.conf
  become: true
