---
## Run apt update on Debian family OSs
- name: "[ClamAV Setup] Perform apt update"
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  when: (ansible_facts['os_family'] == "Debian")

- name: "[ClamAV Setup] Install ClamAV dependencies"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - clamav
    - clamav-daemon
    - clamav-freshclam
    - clamav-base
    - clamdscan
  when: (ansible_facts["os_family"] == "Debian")

