---
collections:
  - name: community.general
    source: https://galaxy.ansible.com
    ## https://galaxy.ansible.com/ui/repo/published/community/general/
    version: 10.6.0

  - name: ansible.posix
    source: https://galaxy.ansible.com
    ## https://galaxy.ansible.com/ui/repo/published/ansible/posix/
    version: 2.0.0

  - name: community.crypto
    source: https://galaxy.ansible.com
    ## https://galaxy.ansible.com/ui/repo/published/community/crypto/
    version: 2.26.1

  # - name: cielito.proxmox
  #   source: https://galaxy.ansible.com
  # ## https://galaxy.ansible.com/ui/repo/published/cielito/proxmox/
  # version: 2.1.1

  - name: my.homelab
    type: dir
    source: collections/my/homelab

roles:
  ## https://galaxy.ansible.com/ui/standalone/roles/staticdev/pyenv/
  - name: staticdev.pyenv
    version: "3.0.0"
