---
collections:
  - name: community.general
    source: https://galaxy.ansible.com
    ## https://galaxy.ansible.com/ui/repo/published/community/general/
    version: 9.1.0

  - name: ansible.posix
    source: https://galaxy.ansible.com
    ## https://galaxy.ansible.com/ui/repo/published/ansible/posix/
    version: 1.5.4

  - name: community.crypto
    source: https://galaxy.ansible.com
    ## https://galaxy.ansible.com/ui/repo/published/community/crypto/
    version: 2.20.0

  # - name: cielito.proxmox
  #   source: https://galaxy.ansible.com
  # ## https://galaxy.ansible.com/ui/repo/published/cielito/proxmox/
  # version: 2.1.0

  - name: my.homelab
    type: dir
    source: collections/my/homelab

roles:
  ## https://galaxy.ansible.com/ui/standalone/roles/staticdev/pyenv/
  - name: staticdev.pyenv
    version: "2.11.0"

  ## https://galaxy.ansible.com/ui/repo/published/robertdebock/roles/content/role/fail2ban/
  # - name: robertdebock.fail2ban
  ## https://github.com/robertdebock/ansible-role-fail2ban/releases
  # version: "5.0.5"
