---
collections:
  - name: community.general
    source: https://galaxy.ansible.com

  # - name: cielito.proxmox
  #   source: https://galaxy.ansible.com

  - name: my.homelab
    type: dir
    source: collections/my/homelab
