# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

includes:
  debug: .tasks/debug.yml

tasks:
  debug-host:
    desc: Debug host parameters
    cmds:
      - task: debug:info

  ansible-requirements:
    desc: Install Ansible requirements with ansible-galaxy
    cmds:
      - cmd: ansible-galaxy collection install -r requirements.yml
