# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

includes:
  debug: .tasks/debug.yml
  ansible: .tasks/ansible.yml

vars:
  ANSIBLE_REQUIREMENTS: requirements.yml

tasks:
  debug-host:
    desc: Debug host parameters
    cmds:
      - task: debug:info

  ansible-requirements:
    desc: Install Ansible requirements with ansible-galaxy
    cmds:
      - cmd: |
          task ansible:galaxy-requirements ANSIBLE_REQUIREMENTS="{{.ANSIBLE_REQUIREMENTS}}"
