---
- name: "UWF disallow TCP ports"
  community.general.ufw:
    rule: deny
    port: "{{ item }}"
    proto: tcp
  become: true
  with_items: "{{ ufw_disallow_tcp_ports }}"
  when: ansible_facts.os_family == "Debian"

- name: "UWF disallow UDP ports"
  community.general.ufw:
    rule: deny
    port: "{{ item }}"
    proto: udp
  become: true
  with_items: "{{ ufw_disallow_udp_ports }}"
  when: ansible_facts.os_family == "Debian"

- name: "Firewalld disallow ports"
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: disabled
  with_items: "{{ firewalld_disallow_ports }}"
  become: true
  when: ansible_facts.os_family == "RedHat"
