---
# tasks file for roles/security/install-firewall
- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "Install firewall"
  ansible.builtin.include_tasks: install-firewall.yml
  when: ansible_facts['os_family'] == "Debian"
