---
- name: "[ClamAV Setup] Check if systemd is installed"
  stat:
    path: /run/systemd/system
  register: systemd_installed
  ignore_errors: true

- name: "[ClamAV Setup] Restart ClamAV systemd service"
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - clamav-daemon.service
    - clamav-freshclam.service
  become: true
  when: systemd_installed.stat.exists == true
