---
- name: "[Debian Family] [Uninstall ClamAV] Uninstall ClamAV dependencies"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  become: true
  with_items:
    - clamav
    - clamav-daemon
    - clamav-freshclam
    - clamav-base
    - clamdscan
  state: present
  when: (ansible_facts["os_family"] == "Debian")

- name: "[RedHat Family] [Uninstall ClamAV] Uninstall ClamAV dependencies"
  ansible.builtin.dnf:
    name:
      - clamav
      - clamav-server
      - clamav-update
      - clamav-data
      - clamav-filesystem
      - clamav-lib
      - clamav-devel
    state: absent
  become: true
  when: (ansible_facts["os_family"] == "RedHat")
