---
- name: "Install virtualenv in Python environment"
  ansible.builtin.shell: |
    {{ pip_bin }} install virtualenv
  args:
    executable: /bin/bash
  become_user: "{{ remote_host_user }}"
  become: true
  register: pip_install_virtualenv
  changed_when: pip_install_virtualenv.rc != 0
