---
# tasks file for python_setup
- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "Include virtualenv install tasks"
  ansible.builtin.include_tasks: install-virtualenv.yml
