---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    # Cache valid for 1 hour
    cache_valid_time: 3600
  when: (ansible_facts.os_family == "Debian") and ("git" not in ansible_facts.packages)

- name: "Install git package"
  ansible.builtin.apt:
    state: present
    name: "git"
  become: true
  when: (ansible_facts.os_family == "Debian") and ("git" not in ansible_facts.packages)

- name: Update DNF cache
  ansible.builtin.dnf:
    update_cache: yes
  become: true
  when: (ansible_facts.os_family == "RedHat") and ("git" not in ansible_facts.packages)

- name: Install git package
  ansible.builtin.dnf:
    name: git
    state: present
  become: true
  when: (ansible_facts.os_family == "RedHat") and ("git" not in ansible_facts.packages)
