---
- name: "Check if ~/.local/bin/pdm exists"
  ansible.builtin.stat:
    path: "/home/{{ remote_host_user }}/.local/bin/pdm"
  register: pdm_bin
  become: true

- name: "Run 'pdm install' in project directory: {{ repo_dest }}"
  ansible.builtin.shell: |
    /home/{{ remote_host_user }}/.local/bin/pdm install
  args:
    executable: /bin/bash
    chdir: "{{ repo_dest }}"
  register: pdm_install_output
  changed_when: false
  become: true
  become_user: "{{ remote_host_user }}"
  when: pdm_bin.stat.exists

- name: "Display output of 'pdm install'"
  ansible.builtin.debug:
    msg: "{{ pdm_install_output.stdout }}"
  when: pdm_bin.stat.exists
