---
- name: "Install virtualenv in pyenv environment"
  ansible.builtin.shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"

    pyenv shell {{ pyenv_python_ver }}
    pyenv exec pip install virtualenv
  args:
    executable: /bin/bash
  become_user: "{{ remote_host_user }}"
  become: true
  register: pyenv_install_virtualenv
  changed_when: pyenv_install_virtualenv.rc != 0
