---
- name: "[ClamAV Setup] Check for existence of /etc/cron.weekly"
  stat:
    path: "/etc/cron.weekly"
  register: cron_weekly

- name: "[ClamAV Setup] Check for existence of /etc/cron.daily"
  stat:
    path: "/etc/cron.daily"
  register: cron_daily

- name: "[ClamAV Setup] Create path /opt/clamav/scans if it does not exist"
  file:
    path: /opt/clamav/scans
    state: directory
  become: true

- name: "[ClamAV Setup] Copy clam_scan.sh to /opt/clamav/scans"
  copy:
    src: files/clam_scan.sh
    dest: /opt/clamav/scans/clam_scan.sh
    mode: "0755"
  become: true

- name: "[ClamAV Setup] Copy weekly_clam_scan.sh to /etc/cron.weekly"
  copy:
    src: files/weekly_clam_scan.sh
    dest: /etc/cron.weekly/weekly_clam_scan.sh
    mode: "0755"
  become: true
  when: (cron_weekly.stat.exists == true)

- name: "[ClamAV Setup] Copy daily_clam_scan.sh to /etc/cron.daily"
  copy:
    src: files/daily_clam_scan.sh
    dest: /etc/cron.daily/daily_clam_scan.sh
    mode: "0755"
  become: true
  when: (cron_daily.stat.exists == true)
