---
- name: "Install requirements"
  apt:
    name: gnupg2
    state: present
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: "Install Tailscale"
  apt:
    name: tailscale
    state: present
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"
