---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    # Cache valid for 1 hour
    cache_valid_time: 3600
  when: (ansible_facts.os_family == "Debian") and ("git" not in ansible_facts.packages)
  become: true

- name: "Install requirements"
  apt:
    name: gnupg2
    state: present
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: "Install Tailscale"
  apt:
    name: tailscale
    state: present
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"
