- name: Set OS-specific dependency list
  set_fact:
    ## Fallback to Debian list if OS family not explicitly listed
    os_deps: "{{ tailscale_dependencies[ansible_facts.os_family] | default(tailscale_dependencies['Debian']) }}"

- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ os_deps }}"
