---
- name: "Include dependency install tasks"
  ansible.builtin.include_tasks: install-dependencies.yml

- name: "Include GPG key add tasks"
  ansible.builtin.include_tasks: add-gpg-key.yml

- name: "Include repository management tasks"
  ansible.builtin.include_tasks: add-repository.yml

- name: "Include tailscale install tasks"
  ansible.builtin.include_tasks: install-tailscale.yml

- name: "Include firewall management tasks"
  ansible.builtin.include_tasks: firewall-allow-tailscale.yml
