---
- name: "Add Tailscale repository"
  apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} main"
    state: present
    filename: tailscale
    update_cache: yes
  become: true
  when: ansible_facts['os_family'] == "Debian"
