---
- name: "Include Tailscale dependency install tasks"
  ansible.builtin.include_tasks: install-dependencies.yml

- name: "Include add Tailscale GPG key tasks"
  ansible.builtin.include_tasks: add-gpg-key.yml

- name: "Include add Tailscale repository tasks"
  ansible.builtin.include_tasks: add-repository.yml

- name: "Include Tailscale install tasks"
  ansible.builtin.include_tasks: install-tailscale.yml

- name: "Include Tailscale systemd tasks"
  ansible.builtin.include_tasks: start-tailscale-service.yml
