---
- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true
    ## One day
    cache_valid_time: 86400
  become: true
  when: ansible_facts.os_family == "Debian"

- name: "Update Tailscale package"
  ansible.builtin.apt:
    name: tailscale
    state: latest
  become: true
  when: ansible_facts.os_family == "Debian"
