---
- name: "Add extra fail2ban jails using the homelab.fail2ban role"
  hosts: all

  vars:
    custom_jails:
      [{ "template": "example.local.j2", "dest": "example/example.local" }]

  tasks:
    - name: "Copy jails"
      ansible.builtin.import_role:
        name: my.weather_monorepo.security.fail2ban
        tasks_from: add-custom-jail.yml

    - name: "Restart fail2ban"
      ansible.builtin.import_role:
        name: my.weather_monorepo.security.fail2ban
        tasks_from: restart-fail2ban.yml
