---
- name: "Generate SSH keys for Codeberg"
  hosts: all

  tasks:
    - name: "Install OpenSSH"
      ansible.builtin.import_role:
        name: my.homelab.ssh
        tasks_from: install-dependencies.yml
    
    - name: "Ensure .ssh dir exists"
      ansible.builtin.import_role:
        name: my.homelab.ssh
        tasks_from: create-ssh-dir.yml

    - name: "Generate Codeberg SSH keys"
      ansible.builtin.import_role:
        name: my.homelab.ssh
        tasks_from: generate-codeberg-ssh-key.yml
