---
- name: Configure ZRAM fractional size & swappiness
  hosts: all
  become: true

  vars:
    ## (0.0 to 1.0, 0.5 = 50%)
    zram_fraction: 0.5
    ## vm.swappiness value
    zram_swappiness: 150

  tasks:
    - name: Configure ZRAM
      ansible.builtin.import_role:
        name: my.homelab.zram
        tasks_from: main.yml
