---
- name: "Install the project with pdm (https://pdm-project.org)"
  hosts: all
  gather_facts: true

  vars:
    repo_dest: "/home/{{ remote_host_user }}/weather-monorepo"
    pdm_script: "install-repo"

  tasks:
    - name: "Gather package facts"
      ansible.builtin.package_facts:
        manager: auto

    - name: "Run PDM install-repo script to install the project"
      ansible.builtin.import_role:
        name: my.weather_monorepo.python.pdm
        tasks_from: run-pdm-script.yml

    # - name: "Install PDM project"
    #   ansible.builtin.import_role:
    #     name: my.weather_monorepo.python.pdm
    #     tasks_from: pdm-install-project.yml
