---
- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: yes
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: "Install Docker packages"
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

    state: present
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == 'Debian'
