---
- name: Load custom facts.
  ansible.builtin.import_tasks: custom_facts.yml
  become: true

- name: Run Darwin specific tasks.
  ansible.builtin.import_tasks: Darwin.yml
  when: ansible_os_family == "Darwin"

- name: Run Debian specific tasks.
  ansible.builtin.import_tasks: Debian.yml
  when: ansible_os_family == "Debian"

- name: Run RedHat specific tasks.
  ansible.builtin.import_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Install pyenv on user level.
  ansible.builtin.import_tasks: install.yml
  become: true
  become_user: "{{ pyenv_owner }}"
  when: pyenv_env == "user"

- name: Install pyenv on system level.
  ansible.builtin.import_tasks: install.yml
  become: true
  when: pyenv_env == "system"
