---
- name: "Install Tailscale and join to network"
  hosts: all
  gather_facts: true

  tasks:
    - ansible.builtin.import_role:
        name: my.homelab.tailscale
        tasks_from: authenticate.yml
