---
- name: "Install Tailscale"
  hosts: all

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.weather_monorepo.facts

    - ansible.builtin.import_role:
        name: my.weather_monorepo.tailscale

    - ansible.builtin.import_role:
        name: my.homelab.tailscale
        tasks_from: firewall-allow-tailscale.yml
