---
- name: "Install crontab"
  hosts: all

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.homelab.base_setup
        tasks_from: gather-facts.yml

    - name: "Include homelab collection's cron.install-crontab role"
      ansible.builtin.import_role:
        name: my.homelab.cron
        tasks_from: install-cron.yml
