---
- name: "Install Tailscale"
  hosts: all

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.homelab.base_setup
        tasks_from: gather-facts.yml

    - ansible.builtin.import_role:
        name: my.homelab.tailscale
