---
- name: "Install Tailscale"
  hosts: all

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.homelab.facts

    - ansible.builtin.import_role:
        name: my.homelab.tailscale
