---
- name: "Install Tailscale and join to network"
  hosts: all

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.homelab.facts

    - ansible.builtin.import_role:
        name: my.homelab.tailscale
        tasks_from: authenticate.yml
