---
- name: "Install Tailscale and join to network"
  hosts: all

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.weather_monorepo.facts

    - ansible.builtin.import_role:
        name: my.weather_monorepo.tailscale
        tasks_from: install-dependencies.yml

    - ansible.builtin.import_role:
        name: my.weather_monorepo.tailscale
        tasks_from: add-gpg-key.yml

    - ansible.builtin.import_role:
        name: my.weather_monorepo.tailscale
        tasks_from: add-repository.yml

    - ansible.builtin.import_role:
        name: my.weather_monorepo.tailscale
        tasks_from: install-tailscale.yml

    - ansible.builtin.import_role:
        name: my.weather_monorepo.tailscale
        tasks_from: start-tailscale-service.yml

    - ansible.builtin.import_role:
        name: my.weather_monorepo.tailscale
        tasks_from: authenticate.yml
