---
- name: "Install pdm (https://pdm-project.org)"
  hosts: all

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.weather_monorepo.facts

    - name: "Call weather-monorepo collection's python/pdm/install-pdm.yml task"
      ansible.builtin.import_role:
        name: my.weather_monorepo.installs.python.pdm
        tasks_from: install-pdm.yml

    - name: "Call weather-monorepo collection's python/pdm/fix-pdm-dir-permissions.yml"
      ansible.builtin.import_role:
        name: my.weather_monorepo.installs.python.pdm
        tasks_from: fix-pdm-dir-permissions.yml
