---
- name: "Install crontab"
  hosts: all

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.weather_monorepo.facts

    - name: "Include homelab collection's cron.install-crontab role"
      ansible.builtin.import_role:
        name: my.weather_monorepo.cron
        tasks_from: install-cron.yml
