---
- name: "Remove Snaps from Ubuntu"
  hosts: all
  gather_facts: true

  tasks:
    - name: "Call homelab collection's remove-snaps role"
      ansible.builtin.import_role:
        name: my.homelab.remove_snaps
