---
- name: "Check if {{ remote_host_user }} SSH private key exists"
  ansible.builtin.stat:
    path: "/home/{{ remote_host_user }}/.ssh/id_rsa"
  # delegate_to: localhost
  register: ssh_key_status
  run_once: true
  become: true

- name: "[DEBUG] /home{{ remote_host_user }}/.ssh/id_rsa existence"
  ansible.builtin.debug:
    msg: "/home/{{ remote_host_user }}/.ssh/id_rsa exists: {{ ssh_key_status.stat.exists }}"

- name: Generate SSH key pair
  ansible.builtin.openssh_keypair:
    path: "/home/{{ remote_host_user }}/.ssh/id_rsa"
    type: rsa
    size: 4096
  run_once: true
  when: ssh_key_status.stat.exists == false
  become: true

- name: "Check if {{ remote_host_user }} SSH private key exists"
  ansible.builtin.stat:
    path: "/home/{{ remote_host_user }}/.ssh/id_rsa"
  # delegate_to: localhost
  register: ssh_key_status
  run_once: true
  become: true

- name: "Check if {{ remote_host_user }} SSH public key exists"
  ansible.builtin.stat:
    path: "/home/{{ remote_host_user }}/.ssh/id_rsa.pub"
  # delegate_to: localhost
  register: ssh_pubkey_status
  run_once: true
  become: true

- name: "Set permissions on the private key"
  ansible.builtin.file:
    path: "/home/{{ remote_host_user }}/.ssh/id_rsa"
    state: file
    mode: "0600"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
  become: true
  when: ssh_key_status.stat.exists == true

- name: "Set permissions on the public key"
  ansible.builtin.file:
    path: "/home/{{ remote_host_user }}/.ssh/id_rsa.pub"
    state: file
    mode: "0644"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
  become: true
  when: ssh_pubkey_status.stat.exists == true

- name: "Debug public key"
  ansible.builtin.command:
    cmd: cat /home/{{ remote_host_user }}/.ssh/id_rsa.pub
  register: public_key
  become: true

- name: "Echo public key"
  debug:
    msg: "Public key: {{ public_key.stdout }}"
