---
- name: "Disable ufw"
  community.general.ufw:
    state: disabled
    policy: "deny"
    logging: "on"
  become: true
  when: ansible_os_family == "Debian"

- name: "Disable firewalld"
  service:
    name: firewalld
    state: stopped
    enabled: false
  become: true
  when: ansible_facts['os_family'] == "Redhat"
