---
- name: "Enable ufw"
  community.general.ufw:
    state: "enabled"
    policy: "deny"
    logging: "on"
  become: true
  when: ansible_os_family == "Debian"

- name: "Enable firewalld"
  service:
    name: firewalld
    state: restarted
    enabled: true
  become: true
  when: ansible_facts['os_family'] == "Redhat"
