---
- name: Install zram package on Debian
  ansible.builtin.apt:
    name: zram-tools
    state: present
    update_cache: true
  when: ansible_distribution == "Debian"

- name: Install zram package on Ubuntu
  ansible.builtin.apt:
    name: zram-config
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Configure zram-generator service
  ansible.builtin.template:
    src: zram-generator.conf.j2
    dest: /etc/systemd/zram-generator.conf
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon to recognize zram-generator config
  ansible.builtin.command: systemctl daemon-reload
  become: true

- name: Start zram device swap unit
  ansible.builtin.systemd:
    name: dev-zram0.swap
    state: started
  become: true

- name: Set vm.swappiness sysctl
  ansible.posix.sysctl:
    name: vm.swappiness
    value: 100
    reload: true

- name: Reboot system after zram-generator config change
  ansible.builtin.reboot:
    reboot_timeout: 600
  become: true
  when: reboot_required | default(true)
