---
# tasks file for collections/my/homelab/zram
- name: Gather package facts (Debian)
  ansible.builtin.package_facts:
    manager: apt
  when: ansible_os_family == "Debian"

- name: Gather package facts (RedHat)
  ansible.builtin.package_facts:
    manager: yum
  when: ansible_os_family == "RedHat"

- name: Detect OS and run appropriate tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian" and ('zram-tools' not in ansible_facts.packages)

- name: Detect OS and run appropriate tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat" and ('dracut-zram' not in ansible_facts.packages)

- name: Run post reboot verification tasks
  ansible.builtin.include_tasks: tasks/post_reboot.yml
