- name: Install zram package on RedHat
  ansible.builtin.yum:
    name: dracut-zram
    state: present
    update_cache: yes

- name: Configure zram-generator on RedHat
  ansible.builtin.template:
    src: zram-generator.conf.j2
    dest: /etc/systemd/zram-generator.conf
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon to recognize zram-generator config
  ansible.builtin.command:
    cmd: systemctl daemon-reload
  become: true

- name: Start zram swap device unit on RedHat
  ansible.builtin.systemd:
    name: dev-zram0.swap
    state: started
  become: true

# Optionally reboot to ensure dynamic unit activation
- name: Reboot system after zram config update
  ansible.builtin.reboot:
    reboot_timeout: 600
  become: true
  when: reboot_required | default(true)
