---
- name: "Install and configure fail2ban package"
  hosts: all

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.homelab.facts

    - name: "Install fail2ban"
      ansible.builtin.import_role:
        name: my.homelab.security.fail2ban
        tasks_from: install-fail2ban.yml

    - name: "Enable fail2ban"
      ansible.builtin.import_role:
        name: my.homelab.security.fail2ban
        tasks_from: enable-fail2ban.yml
