---
- name: "Check for existence of file"
  ansible.builtin.stat:
    path: "{{ del_file_path }}"
  register: del_file
  become: true

- name: "Debug existence of file to delete"
  ansible.builtin.debug:
    msg: "File '{{ del_file_path }}' exists: {{ del_file.stat.exists }}"

- name: "Delete the file"
  ansible.builtin.file:
    path: "{{ del_file_path }}"
    state: absent
  become: true
  when: del_file.stat.exists

- name: "Re-heck for existence of file"
  ansible.builtin.stat:
    path: "{{ del_file_path }}"
  register: del_file2
  become: true
  when: del_file.stat.exists

- name: "Debug existence of file to delete"
  ansible.builtin.debug:
    msg: "File '{{ del_file_path }}' exists: {{ del_file2.stat.exists }}"
  when: del_file.stat.exists
