---
- name: "Generate SSH keys for Github"
  hosts: all

  vars:
    remote_host_user: "dnsuser"

  tasks:
    - name: "Generate SSH keys"
      ansible.builtin.import_role:
        name: my.homelab.ssh
        tasks_from: generate-ssh-key.yml
