---
- name: "Install Docker and Docker Compose"
  hosts: all
  gather_facts: true

  tasks:
    - name: "Call weather-monorepo collection's docker/deb_install-docker.yml task"
      ansible.builtin.import_role:
        name: my.weather_monorepo.installs.docker
        tasks_from: deb_install-docker.yml
      when: ansible_facts['os_family'] == 'Debian'
