---
# defaults file for roles/security/install-firewall

## Ex: "22", "80", "443"
ufw_allow_tcp_ports: [
    ## SSH
    22,
    ## HTTP
    80,
    ## HTTPS
    443,
    ## Postgres
    5432,
    ## pgAdmin web
    15432,
    ## RabbitMQ
    5672,
    ## RabbitMQ management port
    15672,
    ## Redis
    6379,
  ]

ufw_allow_udp_ports: []

## Ex: "22/tcp", "80/tcp", "443/tcp", "5555/udp"
firewalld_allow_ports: [
    ## SSH
    "22/tcp",
    ## HTTP
    "80/tcp",
    ## HTTPS
    "443/tcp",
    ## Postgres
    "5432/tcp",
    ## pgAdmin web
    "15432/tcp",
    ## RabbitMQ
    "5672/tcp",
    ## RabbitMQ management port
    "15672/tcp",
    ## Redis
    "6379/tcp",
  ]

ufw_disallow_tcp_ports: []
ufw_disallow_udp_ports: []
firewalld_disallow_ports: []
