###########
# Ansible #
###########
# ansible_python_interpreter: "/usr/bin/python3"

## User for connection. I use a service account, "ansible_svc"
ansible_ssh_user: "ansible_svc"
## Name of ansible service user account
ansible_svc_user: "ansible_svc"

## Path to service account SSH private key
ansible_ssh_private_key_file: "{{ ansible_ssh_key_dir }}/{{ ansible_svc_user }}"
## Path to service account SSH public key
ansible_ssh_service_public_key_file: "{{ ansible_ssh_key_dir }}/{{ ansible_svc_user }}.pub"
ansible_ssh_public_key_file: "{{ ansible_ssh_key_dir }}/{{ ansible_svc_user }}.pub"

## For path substitution, i.e. "/home/{{ remote_host_user }}"
remote_host_user: "weatheruser"

#############
# Tailscale #
#############

## Generate new keys at: https://login.tailscale.com/admin/settings/keys
tailscale_preauth_key: "tskey-auth-kL3jsw9QAQ11CNTRL-2NdDdu3YWL2zbtXHgeReD25XPtGuD2MXN"

#######
# Git #
#######
git_default_branch_name: "main"
git_user_name: "redjax"
git_user_email: "5534031+redjax@users.noreply.github.com"

##########
# System #
##########

dns_ns: "192.168.1.2"

common_debian_packages:
  [
    "btop",
    "curl",
    "dos2unix",
    "git",
    "htop",
    "ncdu",
    "neovim",
    "tmux",
    "unzip",
    "wget",
    "zip",
    "gnupg2",
  ]

common_redhat_packages: []

##########
# Python #
##########

pypi_token: "<pypi-token>"
test_pypi_token: "<test-pypi-token>"

############
# Crowdsec #
############
crowdsec_enroll_token: "<crowdsec-token>"
