---
# tasks file for base_setup
- name: "Check packages"
  ansible.builtin.package_facts:
    manager: auto

- name: "Include Debian common package install tasks"
  ansible.builtin.include_tasks: deb-install-packages.yml
  when: ansible_facts.os_family == "Debian"

- name: "Include RedHat common package install tasks"
  ansible.builtin.include_tasks: rpm-install-packages.yml
  when: ansible_facts.os_family == "RedHat"
