#SPDX-License-Identifier: MIT-0
---
# tasks file for mosh
- name: "Check packages"
  ansible.builtin.package_facts:
    manager: auto

- ansible.builtin.import_tasks: install.yml
  tags:
    - mosh
    - mosh:install
  when: ("mosh" not in ansible_facts.packages)

- ansible.builtin.import_tasks: firewall-allow.yml
  tags:
    - mosh
    - mosh:configure
