---
- name: "Schedule daily clear of Bash history"
  ansible.builtin.cron:
    name: "Clear bash history every night at 11pm"
    minute: "0"
    hour: "23"
    job: "cat /dev/null > ~/.bash_history"
    user: "{{ remote_host_user }}"
  become: true
  become_user: "{{ remote_host_user }}"
  when: cron_bin.stat.exists
