---
- name: "Check if ~/.bash_history exists"
  ansible.builtin.stat:
    path: "/home/{{ remote_host_user }}/.bash_history"
  become: true
  become_user: "{{ remote_host_user }}"
  register: bash_history

- name: "Clear ~/.bash_history"
  ansible.builtin.shell: cat /dev/null > /home/{{ remote_host_user }}/.bash_history
  become: true
  become_user: "{{ remote_host_user }}"
  when: bash_history.stat.exists
  register: bash_history_clear
  changed_when: bash_history_clear.rc != 0
