---
- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto

# tasks file for configure/configure-cron
- name: "Check if Cron is installed"
  ansible.builtin.include_tasks: check-cron-installed.yml
  # register: cron_bin

- name: "Create crontab entry"
  ansible.builtin.include_tasks: schedule-clear-bash-history.yml
  when: cron_bin.stat.exists
