---
- name: "Add /etc/fail2ban/fail2ban.local"
  ansible.builtin.template:
    src: fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    mode: "0644"
    # backup: true
  become: true

- name: "Add /etc/fail2ban/jail.local"
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: "0644"
    # backup: true
  become: true

- name: "Add /etc/fail2ban/jail.d/sshd.local"
  ansible.builtin.template:
    src: jail.d/ssh/sshd.local.j2
    dest: /etc/fail2ban/jail.d/sshd.local
    mode: "0644"
  become: true

- name: "Add /etc/fail2ban/jail.d/dropbear.local"
  ansible.builtin.template:
    src: jail.d/ssh/dropbear.local.j2
    dest: /etc/fail2ban/jail.d/dropbear.local
    mode: "0644"
  become: true

- name: "Add /etc/fail2ban/jail.d/selinux_ssh.local"
  ansible.builtin.template:
    src: jail.d/ssh/selinux_ssh.local.j2
    dest: /etc/fail2ban/jail.d/selinux_ssh.local
    mode: "0644"
  become: true
