---
- name: "Run database initialization scripts"
  hosts: all
  gather_facts: true

  vars:
    repo_dest: "/home/{{ remote_host_user }}/weather-monorepo"
    nox_session_name: "init-db"

  tasks:
    - name: "Gather package facts"
      ansible.builtin.package_facts:
        manager: auto

    - name: "Run database initialization session in nox"
      ansible.builtin.import_role:
        name: my.weather_monorepo.python.pdm
        tasks_from: run-nox-session.yml
