---
- name: "Check if dest '{{ repo_dest }}' exists"
  ansible.builtin.stat:
    path: "{{ repo_dest }}"
  register: repo_dest_dir
  run_once: true
  become: true

- name: "Clone repository: {{ repo_url }} to {{ repo_dest }}"
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    accept_hostkey: true
    key_file: "{{ gh_ssh_key }}"
    refspec: "+refs/pull/*:refs/heads/*"
    version: "{{ repo_checkout_branch }}"
  when: ("git" in ansible_facts.packages) and (repo_dest_dir.stat.exists)
  become: true
  become_user: "{{ remote_host_user }}"
  environment:
    ## Avoid hangs when http(s) password is missing
    GIT_TERMINAL_PROMPT: "0"
