---
- name: "Check if dest '{{ repo_dest }}' exists"
  ansible.builtin.stat:
    path: "{{ repo_dest }}"
  register: repo_dest_dir
  run_once: true
  become: true

- name: "Clone repository: {{ repo_url }} to {{ repo_dest }}"
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    accept_hostkey: true
    key_file: "{{ gh_ssh_key }}"
  when: ("git" in ansible_facts.packages) and (not repo_dest_dir.stat.exists)
  become: true
  become_user: "{{ remote_host_user }}"

- name: "Check that repostitory cloned successfully"
  ansible.builtin.stat:
    path: "{{ repo_dest }}"
  register: cloned_repo_dest
  run_once: true
  become: true

- name: "[DEBUG] {{ repo_dest }} existence"
  ansible.builtin.debug:
    msg: "{{ repo_dest }} exists: {{ cloned_repo_dest.stat.exists }}"
