---
- name: "Install fail2ban package"
  hosts: all

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.weather_monorepo.facts

    - name: "Install fail2ban"
      ansible.builtin.import_role:
        name: my.weather_monorepo.security.fail2ban
        tasks_from: install-fail2ban.yml
