---
- name: "UWF allow TCP ports"
  # community.general.ufw:
  #   policy: allow
  #   port: "{{ item }}"
  #   proto: tcp
  ansible.builtin.shell: |
    ufw allow {{ item }}/tcp
  become: true
  register: ufw_allow_tcp_output
  with_items: "{{ ufw_allow_tcp_ports }}"
  when: (ansible_facts.os_family == "Debian") and ("ufw" in ansible_facts.packages)

- name: "Debug UFW allow tcp ports output"
  ansible.builtin.debug:
    var: ufw_allow_tcp_output.stdout
  when: (ansible_facts.os_family == "Debian") and ("ufw" in ansible_facts.packages)

- name: "UWF allow UDP ports"
  # community.general.ufw:
  #   policy: allow
  #   port: "{{ item }}"
  #   proto: udp
  ansible.builtin.shell: |
    ufw allow {{ item }}/udp
  register: ufw_allow_udp_output
  become: true
  with_items: "{{ ufw_allow_udp_ports }}"
  when: (ansible_facts.os_family == "Debian") and ("ufw" in ansible_facts.packages)

- name: "Debug UFW allow udp ports output"
  ansible.builtin.debug:
    var: ufw_allow_udp_output.stdout
  when: (ansible_facts.os_family == "Debian") and ("ufw" in ansible_facts.packages)

- name: "Firewalld allow ports"
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: "{{ firewalld_allow_ports }}"
  become: true
  when: ansible_facts.os_family == "RedHat"

- name: "Reload UFW firewall"
  ansible.builtin.command: ufw reload
  become: true
  when: ansible_facts.os_family == "Debian"

- name: Reload firewalld
  command: firewall-cmd --reload
  become: true
  when: ansible_facts.os_family == "RedHat"
