---
- name: "[DEBUG] Debug custom jails"
  ansible.builtin.debug:
    msg: "[Custom Jail] template: {{ item['template'] }}, copy to: {{ item['dest'] }}"
  with_items:
    - "{{ custom_jails }}"

- name: "Create jail subdirectories"
  ansible.builtin.file:
    path: "/etc/fail2ban/jail.d/{{ item['dest'] | dirname }}"
    state: directory
    mode: "0755"
    group: root
    owner: root
  become: true
  with_items:
    - "{{ custom_jails }}"

- name: "Add custom jail"
  ansible.builtin.template:
    src: "{{ item['template'] }}"
    dest: "/etc/fail2ban/jail.d/{{ item['dest'] }}"
    mode: "0644"
  become: true
  with_items:
    - "{{ custom_jails }}"
