---
- name: "Check for existence of /etc/fail2ban/fail2ban.conf"
  ansible.builtin.stat:
    path: "/etc/fail2ban/fail2ban.conf"
  register: fail2ban_conf
  become: true

- name: "Check for existence of /etc/fail2ban/fail2ban.conf.orig"
  ansible.builtin.stat:
    path: "/etc/fail2ban/fail2ban.conf.orig"
  register: fail2ban_conf_orig
  become: true

- name: "Check for existence of /etc/fail2ban/jail.conf"
  ansible.builtin.stat:
    path: "/etc/fail2ban/jail.conf"
  register: fail2ban_jail_conf
  become: true

- name: "Check for existence of /etc/fail2ban/jail.conf.orig"
  ansible.builtin.stat:
    path: "/etc/fail2ban/jail.conf.orig"
  register: fail2ban_jail_conf_orig
  become: true

- name: "Backup /etc/fail2ban/fail2ban.conf"
  ansible.builtin.copy:
    src: /etc/fail2ban/fail2ban.conf
    dest: /etc/fail2ban/fail2ban.conf.orig
    remote_src: true
    mode: "0644"
  become: true
  when: (not fail2ban_conf_orig.stat.exists) and (fail2ban_conf.stat.exists)

- name: "Backup /etc/fail2ban/jail.conf"
  ansible.builtin.copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.conf.orig
    remote_src: true
    mode: "0644"
  become: true
  when: (not fail2ban_jail_conf_orig.stat.exists) and (fail2ban_jail_conf.stat.exists)
