---
- name: "Install fail2ban package"
  ansible.builtin.package:
    name:
      - python3-systemd
      - fail2ban
    state: present
  become: true
  when: ("fail2ban" not in ansible_facts.packages)
