---
default_shell: "{{ ansible_user_shell | basename }}"
shell_init: "{{ lookup('vars', default_shell + '_init') }}"

bash_init:
  global:
    - /etc/profile
    - /etc/bash.bashrc
  local:
    - "{{ ansible_user_dir }}/.bash_profile"
    - "{{ ansible_user_dir }}/.bashrc"

zsh_init:
  global:
    - /etc/zshenv
    - /etc/zprofile
    - /etc/zshrc
  local:
    - "{{ ansible_user_dir }}/.zshenv"
    - "{{ ansible_user_dir }}/.zprofile"
    - "{{ ansible_user_dir }}/.zshrc"

fish_init:
  global:
    - /etc/fish/config.fish
  local:
    - "{{ ansible_user_dir }}/.config/fish/config.fish"
