---
- name: "[DEBUG] Debug Github ssh key values"
  ansible.builtin.debug:
    msg:
      - "Remote host user: {{ remote_host_user }}"
      - "SSH key path: {{ remote_host_user }}/.ssh/github_id_rsa"

- name: "Ensure openssh-server is installed"
  ansible.builtin.package:
    name: openssh-server
    state: present
  become: true

- name: "Create .ssh directory if it doesn't exist"
  ansible.builtin.file:
    path: "/home/{{ remote_host_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
  become: true

- name: "Generate SSH key for GitHub"
  ansible.builtin.shell:
    cmd: ssh-keygen -t rsa -b 4096 -f /home/{{ remote_host_user }}/.ssh/github_id_rsa -N ""
  args:
    creates: "/home/{{ remote_host_user }}/.ssh/github_id_rsa" # Skip if key already exists
  become: true

- name: "Set permissions on the private key"
  ansible.builtin.file:
    path: "/home/{{ remote_host_user }}/.ssh/github_id_rsa"
    state: file
    mode: "0600"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
  become: true

- name: "Set permissions on the .ssh directory"
  ansible.builtin.file:
    path: "/home/{{ remote_host_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
  become: true

- name: "Ensure .ssh/config exists and configure GitHub"
  ansible.builtin.lineinfile:
    path: "/home/{{ remote_host_user }}/.ssh/config"
    line: |
      Host github.com
        User git
        IdentityFile ~/.ssh/github_id_rsa
    state: present
    create: true
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
  become: true

- name: "Debug public key"
  ansible.builtin.command:
    cmd: cat /home/{{ remote_host_user }}/.ssh/github_id_rsa.pub
  register: public_key
  become: true

- name: "Echo public key"
  debug:
    msg: "Public key for GitHub: {{ public_key.stdout }}"
