---
- name: "Install ClamAV & do base setup"
  hosts: all
  gather_facts: true

  tasks:
    - name: "Include homelab collection's clamav role"
      ansible.builtin.import_role:
        name: my.homelab.security.clamav
