---
- name: "Setup common ClamAV scans"
  hosts: all

  tasks:
    - name: "Gather the package facts"
      ansible.builtin.import_role:
        name: my.homelab.base_setup
        tasks_from: gather-facts.yml

    - name: "Include homelab collection's clamav.configure_scans role"
      ansible.builtin.import_role:
        name: my.homelab.security.clamav
        tasks_from: configure_scans.yml

    - name: "Include homelab collection's clamav.restart_clamav_systemd role"
      ansible.builtin.import_role:
        name: my.homelab.security.clamav
        tasks_from: restart_clamav_systemd.yml
