---
- name: "Update apt repo and cache"
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  when: ansible_facts.os_family == "Debian"

- name: "Upgrade all packages"
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: true
  become: true
  when: ansible_facts.os_family == "Debian"
