---
- name: "Update dnf repo and cache"
  ansible.builtin.dnf:
    update_cache: true
    update_only: true
  become: true
  when: ansible_facts.os_family == "RedHat"

- name: "Upgrade all packages"
  ansible.builtin.dnf:
    name: "*"
    state: latest
    autoremove: true
  become: true
  when: ansible_facts.os_family == "RedHat"
