---
- name: "Check remote CPU Architecture"
  hosts: all

  tasks:
    - name: "Print CPU architecture"
      ansible.builtin.debug:
        ## Use ansible_architecture builtin
        msg: "CPU Architecture: {{ ansible_architecture }}"
