---
- name: "Create new user"
  ansible.builtin.user:
    name: "{{ new_user_name }}"
    comment: "{{ new_user_comment | default('Created by Ansible')}}"
    groups: docker,{{ new_user_name }}
    create_home: true
    shell: "{{ new_user_shell | default('/bin/bash') }}"
    append: true
    state: present
    generate_ssh_key: "{{ new_user_generate_ssh_key | default(true) }}"
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
