---
- name: "[DEBUG] Debug new user values"
  ansible.builtin.debug:
    msg:
      - "new_user_name: {{ new_user_name }}"
      - "new_user_comment: {{ new_user_comment | default('Created by Ansible') }}"
      - "new_user_shell: {{ new_user_shell | default('/bin/bash') }}"
      - "new_user_ssh_keypath: {{ new_user_ssh_keypath | default('.ssh/id_rsa') }}"

- name: "Create user: {{ new_user_name }}"
  ansible.builtin.user:
    name: "{{ new_user_name }}"
    home: "/home/{{ new_user_name }}"
    state: present
    shell: /bin/bash
    groups:
      - sudo
  become: true
  when: not remove_user | default(false)

- name: "Add {{ new_user_name }} to passwordless sudoers"
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ new_user_name }}"
    content: "{{ new_user_name }} ALL=(ALL) NOPASSWD:ALL"
    owner: root
    group: root
    mode: "0440"
  become: true
