---
- name: "Ensure 'wheel' group exists"
  group:
    name: wheel
    state: present
  become: true

- name: "Allow 'wheel' group passwordless sudo"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  become: true

- name: "Add user '{{ ansible_svc_user }}' to 'wheel' group"
  user: name="{{ ansible_svc_user }}"
    groups=wheel
    append=yes
    state=present
    createhome=yes
  become: true

- name: "Authorize SSH keys for {{ ansible_svc_user }}"
  ansible.posix.authorized_key:
    user: "{{ ansible_svc_user }}"
    state: present
    key: "{{ item }}"
  with_file:
    - "{{ ansible_ssh_service_public_key_file }}"
    - "{{ ansible_ssh_public_key_file }}"
  become: true
