---
- name: Install unattended-upgrades and apt-listchanges
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
    update_cache: true
  become: true
  when: ansible_facts.os_family == "Debian"

- name: Enable unattended-upgrades
  ansible.builtin.command:
    cmd: echo "unattended-upgrades unattended-upgrades/enable_auto_updates boolean true" | debconf-set-selections
  ignore_errors: true
  become: true
  when: ansible_facts.os_family == "Debian"

- name: Reconfigure unattended-upgrades
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
  become: true
  when: ansible_facts.os_family == "Debian"

- name: Restart unattended-upgrades service
  ansible.builtin.systemd:
    name: apt-daily.timer
    state: restarted
  become: true
  when: ansible_facts.os_family == "Debian"
