---
- name: "[DEBUG] Print apps to be installed by pipx"
  ansible.builtin.debug:
    msg: "{{ pipx_apps_list }}"

- name: "Install pipx apps"
  ansible.builtin.shell: |
    {{ pipx_bin }} install {{ item }}
  args:
    executable: /bin/bash
  with_items: "{{ pipx_apps_list }}"
  become_user: "{{ remote_host_user }}"
  become: true
  register: pipx_app_install
  changed_when: pipx_app_install.rc != 0
