---
- name: "Install pipx in pyenv environment"
  ansible.builtin.shell: |
    {{ python_bin }} -m pip install pipx
  args:
    executable: /bin/bash
  become_user: "{{ remote_host_user }}"
  become: true
  register: pyenv_install_pipx
  changed_when: pyenv_install_pipx.rc != 0

- name: "Run pipx ensurepath"
  ansible.builtin.shell: |
    {{ python_bin }} -m pipx ensurepath
  become_user: "{{ remote_host_user }}"
  become: true
  register: pipx_ensurepath
  changed_when: pipx_ensurepath.rc != 0
