---
- name: Install kopia
  apt:
    pkg:
      - kopia
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Install kopia
  ansible.builtin.dnf:
    name:
      - kopia
    state: present
  become: true
  when: ansible_os_family == "RedHat"
