- name: Add /var/log/kopia directory for cron logs
  file:
    path: /var/log/kopia
    state: directory
    owner: root
    group: root
    mode: 0750
  become: true

- name: Add logrotate entry for logs
  template:
    src: kopia.logrotate.j2
    dest: /etc/logrotate.d/kopia
    owner: root
    group: root
    mode: 0644
  become: true
