- name: Create systemd service for Kopia
  template:
    src: kopia.service.j2
    dest: /etc/systemd/system/kopia.service
    owner: root
    group: root
    mode: 0644
  become: true

- name: Reload systemd to pick up Kopia service
  systemd:
    daemon_reload: true
  become: true

- name: Enable & start Kopia service
  systemd:
    name: kopia
    enabled: true
    state: started
  become: true
