---
- name: Create group {{ pyenv_group }}.
  ansible.builtin.group:
    name: "{{ pyenv_group }}"
    system: true
    state: present

- name: Add user to the group {{ pyenv_group }}.
  ansible.builtin.user:
    name: "{{ pyenv_owner }}"
    groups: "{{ pyenv_group }}"
    append: true
    state: present

- name: Ensure proper permissions for {{ pyenv_path }}.
  ansible.builtin.file:
    path: "{{ pyenv_path }}"
    owner: root
    group: "{{ pyenv_group }}"
    mode: g+rwx
    recurse: true
    state: directory
