---
- name: "Check if crowdsec service is installed"
  stat:
    path: /lib/systemd/system/crowdsec.service
  register: systemd_installed
  ignore_errors: true

- name: "Restart crowdsec systemd service"
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - crowdsec.service
  become: true
  when: systemd_installed.stat.exists == true
